version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./backend/go.mod:/app/backend/go.mod
      - ./backend/go.sum:/app/backend/go.sum
  db:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    restart: always
    networks:
      - lesson
networks:
  lesson: